---
volumes:
  data:

services:
  postgres:
    image: postgres:15.6-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: .env.local
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - jaeger
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file: .env.local
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - otel-collector
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file: .env.local
    depends_on:
      - server
