receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:

exporters:
  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: jaeger:4317
    tls:
      insecure: true

      #service:
      #  pipelines:
      #    exporters: [otlp/jaeger]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/jaeger]
