// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/FachschaftMathPhysInfo/pepp/server/models"
)

type User interface {
	IsUser()
}

type EventTutorRoomPair struct {
	Tutors        []*models.Tutor `json:"tutors,omitempty"`
	Room          *models.Room    `json:"room,omitempty"`
	Registrations *int            `json:"registrations,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
